### ISSUE TITLE
how your app can play audio in the background WITHOUT any SERVICE ? (please help)

### ISSUE THREAD

**Issue by sadjadtalakoob74** [nzkozar/ExoplayerExample#4]
Hi, 
i have a big problem to use service in the official EXOPLAYER app , so i find your version that can play the audio without any service. could you do me a favor and explain which part of your version of solve this problem ?

thanks alot.

**Comment by nzkozar** [comment]
Hi. First a small disclaimer: this example is quite old, not featuring the latest version of exoplayer or targeting the latest versions of android. If you tried targeting the latest versions of both exoplayer and Android OS, the example might not work. I also haven't been developing Android for the last 2 years, so I'm not on track with the current dev situation.

As far as I remember this example only works in the foreground (while the app is open) navigating out of the app, the playback will probably stop.

Older versions of Android had much more loose rules on background services and execution of "heavy" lifting like audio playback without the use of a service. So one reason why this example might still work is because it is not targeting the latest android version. Try changing the target SDKs of this example to the latest SDK version and let me know if the example still works. I'd love to know, but just don't have the time to dive into updating this example.

I'm happy to hear that it is of some help to a bunch of people tho.

**Comment by sadjadtalakoob74** [comment]
> Hi. First a small disclaimer: this example is quite old, not featuring the latest version of exoplayer or targeting the latest versions of android. If you tried targeting the latest versions of both exoplayer and Android OS, the example might not work. I also haven't been developing Android for the last 2 years, so I'm not on track with the current dev situation.
> 
> As far as I remember this example only works in the foreground (while the app is open) navigating out of the app, the playback will probably stop.
> 
> Older versions of Android had much more loose rules on background services and execution of "heavy" lifting like audio playback without the use of a service. So one reason why this example might still work is because it is not targeting the latest android version. Try changing the target SDKs of this example to the latest SDK version and let me know if the example still works. I'd love to know, but just don't have the time to dive into updating this example.
> 
> I'm happy to hear that it is of some help to a bunch of people tho.

Hi,
Thanks for explaining well.
Yeah it's work properly in api28 as well 😄.
It makes me wonder how but it works without any foreground service implementation!!!
